### ISSUE TITLE
loi form quan ly phong ban

### ISSUE THREAD

**Issue by HuynhNhatLinh** [doanh20cm/CNPM#1]
This exception was originally thrown at this call stack:
    [External Code]
    Quan_li_nhan_su.QLNhanVienPhongBan.dgvNhanVienPhongBan_DataBindingComplete(object, System.Windows.Forms.DataGridViewBindingCompleteEventArgs) in QLNhanVienPhongBan.cs
    [External Code]
    Quan_li_nhan_su.QLNhanVienPhongBan.GetData.AnonymousMethod__3_1(object, System.ComponentModel.RunWorkerCompletedEventArgs) in QLNhanVienPhongBan.cs
    [External Code]

**Comment by doanhidm1** [comment]
fixed in least commit
